schemaVersion: "v2"

name: returns-receive-ui
team: returns
description: A simple UI to accept or reject a digital return
technology: node

deployment:
  kubernetes:
    namespace: returns
    versionKey: microservice.image.tag
    env:
      staging:
        dependencies:
          - name: microservice
            version: "*"
            repository: https://charts.parcellab.dev
        metadata:
          slackChannelId: XXX # returns-deployment-channel
          statusUrl: https://argocd.staging.parcellab.dev/applications/returns-receive-ui
          url: https://returns-receive-ui.staging.parcellab.dev
        values:
          microservice:
            ingress:
              enabled: true
              annotations:
                nginx.ingress.kubernetes.io/auth-signin: https://oauth.staging.parcellab.dev/oauth2/start?rd=https://$host$request_uri
                nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth?allowed_groups=parcellab-employee,/parcellab-employee,/external-workers,external-workers
                nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
              hosts:
                - host: returns-receive-ui.staging.parcellab.dev
                  paths:
                    - backend:
                        service:
                          name: returns-receive-ui
                          port:
                            name: http
                      path: /
                      pathType: Prefix
              tls:
                - hosts:
                    - returns-receive-ui.staging.parcellab.dev
